// import '@fontsource/monaspace-argon'
import '@fontsource/monaspace-neon'
// import '@fontsource/monaspace-xenon'
import '@fontsource/monaspace-krypton'
import '@fontsource/ibm-plex-mono'
import '@fontsource-variable/ibm-plex-sans'
import '@fontsource/ibm-plex-serif'
import '@ibm/plex-math/scss/index.scss'
import '@ibm/plex-mono/scss/index.scss'
import '@ibm/plex-sans/scss/index.scss'
import '@ibm/plex-serif/scss/index.scss'
// import '@fontsource/monaspace-radon'
import './style.css'